### ISSUE TITLE
Some Command Duplicate on bot-ai-chat channel

### ISSUE THREAD

**Issue by ghost** [quinchs/SwissbotCore#1]
Hi, I am Chanakan5591#4233 or as nick as "Swissbot in C#, Minuet in G". I don't know if this is a bug or it is expected. Some command that you run on bot-ai-chat channel like "support,  modwars, quinasking" will duplicate. The first message will show as normal Uppercase and Lowercase text, but the second message do send all in lowercase. At first I was going to fix the bug in the code but I rarely understand C#. So I might learn it and will pull request it in the future. Thank you!

**Comment by quinchs** [comment]
The reason it duplicates is because the ai has see the message `*modwars` before and it knows the response is the modwars command image, so the ai will post a response will be the same as doing the command. i can disable these keywords but this is not a big issue.
